paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: No se encontraron productos
        "500":
          description: Error al obtener los productos
  /api/products/{id}:
    get:
      summary: Obtiene la información de un producto especifico por su ID
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: ID del producto a obtener
        schema:
          type: string
      responses:
        "200":
          description: Producto obtenido correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error al obtener el producto
    put:
      summary: Actualiza un producto existente
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: ID del producto a actualizar
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateProduct"
      responses:
        "200":
          description: Producto actualizado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Producto no encontrado
        "500":
          description: Error al actualizar el producto
    delete:
      summary: Elimina un producto existente
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: ID del producto a eliminar
        schema:
          type: string
      responses:
        "200":
          description: Producto eliminado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error al eliminar el producto
  /api/products/:
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/createProduct"
      responses:
        "201":
          description: Producto creado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error al crear el producto
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Identificador del producto creado por MongoDB
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código del producto
        stock:
          type: number
          description: Stock del producto
        owner:
          type: string
          description: Creador del producto
      example:
        _id: ObjectId("60f3b3b3b3b3b3b3b3b3b3b3")
        title: "Producto 1"
        description: "Descripción del producto 1"
        price: 100
        thumbnail: "https://www.google.com"
        code: "1234"
        stock: 10
        owner: "admin"
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código del producto
        stock:
          type: number
          description: Stock del producto
        owner:
          type: string
          description: Creador del producto
      example:
        title: "Producto 1"
        description: "Descripción del producto 1"
        price: 100
        thumbnail: "https://www.google.com"
        code: "1234"
        stock: 10
        owner: "admin"
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: string
          description: URL de la imagen del producto
        code:
          type: string
          description: Código del producto
        stock:
          type: number
          description: Stock del producto
        owner:
          type: string
          description: Creador del producto
      example:
        title: "Producto 1"
        description: "Descripción del producto 1"
        price: 100
        thumbnail: "https://www.google.com"
        code: "1234"
        stock: 10
        owner: "admin"